export const queryKeys = {
  projects: ['projects'] as const,
  project: (id: string) => ['projects', id] as const,
  files: (projectId: string) => ['projects', projectId, 'files'] as const,
  file: (fileId: string) => ['files', fileId] as const,
  storage: ['workspace', 'storage'] as const,
  adminUsers: (role?: string) => ['admin', 'users', role ?? 'all'] as const,
  adminRoster: ['admin', 'roster'] as const,
  instructorRoster: ['instructor', 'roster'] as const,
  instructorAssignments: ['instructor', 'assignments'] as const,
  instructorAssignment: (id: string) => ['instructor', 'assignments', id] as const,
  studentAssignments: ['student', 'assignments'] as const,
  studentAssignment: (id: string) => ['student', 'assignments', id] as const,
  submission: (projectId: string) => ['projects', projectId, 'submission'] as const,
  lineComments: (fileId: string) => ['files', fileId, 'comments'] as const,
  notifications: ['notifications'] as const,
  instructorGuidelines: ['instructor', 'guidelines'] as const,
  studentGuidelines: ['student', 'guidelines'] as const,
  adminSmtpSettings: ['admin', 'smtp-settings'] as const,
  instructorReport: ['instructor', 'report'] as const,
  adminUsersPaged: (params: Record<string, unknown>) => ['admin', 'users', 'paged', params] as const,
  adminUserDetail: (id: string) => ['admin', 'users', id] as const,
  adminUserAggregates: (id: string) => ['admin', 'users', id, 'aggregates'] as const,
  instructorProfile: ['instructor', 'profile'] as const,
  studentInstructorProfile: (id: string) => ['student', 'instructors', id, 'profile'] as const,
  studentProfile: ['student', 'profile'] as const,
  instructorStudentProfile: (id: string) => ['instructor', 'students', id, 'profile'] as const,
};
